Pytorch는 Tensorflow와 더불어 가장 널리 사용되는 딥러닝 프레임워크

다차원 배열인 Tensor를 기본 연산단위로 활용한다

https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

1. 라이브러리 불러오기


In [1]:
import torch
import numpy as np

2. 텐서 만들기

* 텐서는 List와 Numpy Array에서 만들 수 있음

* 리스트는 파이썬에서 배열을 다루는 데이터 타입

* Numpy는 배열 연산을 위한 라이브러리로 데이터 과학에서 널리 사용됨

* Tensor는 numpy의 기능을 참고하여 딥러닝 연산에 필요한 기능들을 제공. 문법이 유사한 경우가 많음

In [2]:
# 리스트에서 만들기

data1 = [1,2,3]  # 리스트
t1= torch.tensor(data1)  # 텐서로 변환

In [3]:
print(data1)
print(t1)

# 출력형태가 리스트와 텐서가 다르게 나타남

[1, 2, 3]
tensor([1, 2, 3])


In [4]:
data2 = [[1,2,3],[4,5,6]] # 2차 배열
t2 = torch.tensor(data2)

In [5]:
# Numpy에서 만들기

data3= np.array([1,2,3]) # numpy 배열 만들기
t3 = torch.tensor(data3)

In [6]:
t3

tensor([1, 2, 3])

* 랜덤이나 상수로도 만들 수 있음

In [7]:
t4 = torch.rand(2,3) # 2 x 3 텐서만들기

In [8]:
t4

tensor([[0.1226, 0.1430, 0.2524],
        [0.7658, 0.0019, 0.6566]])

In [9]:
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

3. 텐서 속성

In [11]:
t4.shape  # 사이즈 확인

torch.Size([2, 3])

In [12]:
t4.dtype  # 데이터 타입 확인

torch.float32

In [13]:
t4.device # 저장 위치 확인

device(type='cpu')

4. 저장 위치 
* 기본값은 CPU 저장이며, .to()를 사용하여 GPU로 옮길 수 있다. 

* Colab에서는 런타임에서 런타임 유형을 GPU로 변경하면 GPU 사용 가능함

* cuda는 nvidia의 딥러닝 연산 엔진

In [14]:
# GPU 사용 확인

torch.cuda.is_available()  # GPU 사용 가능하면 True, 아니면 false

True

In [15]:
t4

tensor([[0.1226, 0.1430, 0.2524],
        [0.7658, 0.0019, 0.6566]])

In [16]:
t5=t4.to('cuda') # GPU로 옮김

In [17]:
t5  

tensor([[0.1226, 0.1430, 0.2524],
        [0.7658, 0.0019, 0.6566]], device='cuda:0')

5. 텐서 연산
* 사칙연산 및 행렬 연산 가능함 
  - 사칙연산은 동일 위치끼리 연산

In [18]:
t6 = torch.tensor([1,2,3])
t7 = torch.tensor([2,3,4])

In [19]:
t6+t7

tensor([3, 5, 7])

In [20]:
t6 * t7

tensor([ 2,  6, 12])

In [21]:
t7/t6

tensor([2.0000, 1.5000, 1.3333])

In [22]:
t6 @ t7  # 행렬 곱

tensor(20)

In [23]:
t5.T  # Transpose

tensor([[0.1226, 0.7658],
        [0.1430, 0.0019],
        [0.2524, 0.6566]], device='cuda:0')

6. 타입 및 디바이스 관련
* 파이토치의 타입은 파이썬 기본 타입보다 종류가 많음
https://pytorch.org/docs/stable/tensors.html
* 디바이스 다르면 연산 안 됨
* GPU 저장된 변수는 numpy로 변환 안됨

In [24]:
print(t6.dtype, t7.dtype)

torch.int64 torch.int64


In [25]:
# 데이터 타입 변경
t7 = t7.type(torch.float)

In [26]:
t8 = t7.to('cuda')

In [28]:
t7+t8

RuntimeError: ignored

Expected all tensors to be on the same device

연산은 같은 디바이스에만 가능함

In [38]:
t8.numpy()

TypeError: ignored

TypeError: can't convert cuda:0 device type tensor to numpy

numpy배열 변환 전에 CPU로 디바이스 옮겨야 가능함

In [30]:
t8.to('cpu').numpy()

array([2., 3., 4.], dtype=float32)

디바이스를 옮기는 것은 리소스를 많이 사용하므로 최소한으로 하는 것이 좋음

7. 인덱싱

* [start:end]
* start는 0부터, end는 미포함
* -1은 마지막을 의미

In [31]:
t9 = torch.rand(10)

In [32]:
t9

tensor([0.1618, 0.1289, 0.0601, 0.8309, 0.4461, 0.6755, 0.2637, 0.0057, 0.0357,
        0.7103])

In [33]:
t9[0]  # 첫번째

tensor(0.1618)

In [34]:
t9[1:5]

tensor([0.1289, 0.0601, 0.8309, 0.4461])

In [35]:
t9[-2:-1]  # 뒤에서 2번째 요소만 가져옴, -1은 end 자리이므로 미포함

tensor([0.0357])

In [36]:
t9[-2:]  # start나 end가 비어있으면 처음 또는 끝까지임

tensor([0.0357, 0.7103])

In [37]:
t9[:] # 시작과 끝이 생략되면 전부 다

tensor([0.1618, 0.1289, 0.0601, 0.8309, 0.4461, 0.6755, 0.2637, 0.0057, 0.0357,
        0.7103])

여러 차원 텐서도 동일한 기준이 적용됩니다. 

In [39]:
# pytorch에서는 이미지를 [N, C, H, W] 로 지정합니다

t10 = torch.rand(2,3,5,5) # 5x5 RGB 이미지 2장 예시

In [40]:
t10

tensor([[[[0.1100, 0.7883, 0.5993, 0.9477, 0.8325],
          [0.2156, 0.7145, 0.4367, 0.0315, 0.3926],
          [0.4098, 0.7815, 0.9958, 0.2380, 0.2621],
          [0.2842, 0.9633, 0.6489, 0.2329, 0.5306],
          [0.1958, 0.7084, 0.5265, 0.9228, 0.5801]],

         [[0.5621, 0.2295, 0.3116, 0.4237, 0.4300],
          [0.3891, 0.1177, 0.6552, 0.4001, 0.8315],
          [0.5020, 0.1340, 0.3936, 0.3479, 0.5690],
          [0.9737, 0.6566, 0.9133, 0.8860, 0.6550],
          [0.8897, 0.1659, 0.5994, 0.2447, 0.4253]],

         [[0.6758, 0.2233, 0.1595, 0.3236, 0.2762],
          [0.3482, 0.2082, 0.3498, 0.7722, 0.9337],
          [0.7588, 0.4611, 0.8162, 0.0691, 0.7052],
          [0.7427, 0.7207, 0.9146, 0.5633, 0.0325],
          [0.7342, 0.2215, 0.5160, 0.1582, 0.3223]]],


        [[[0.6049, 0.1758, 0.4152, 0.0223, 0.8323],
          [0.1581, 0.3767, 0.5381, 0.7620, 0.2892],
          [0.6185, 0.9758, 0.2122, 0.0867, 0.3426],
          [0.7099, 0.2646, 0.0581, 0.2585, 0.3734],
    

In [43]:
img1 = t10[0] # 첫번째 이미지

In [42]:
img1

tensor([[[0.1100, 0.7883, 0.5993, 0.9477, 0.8325],
         [0.2156, 0.7145, 0.4367, 0.0315, 0.3926],
         [0.4098, 0.7815, 0.9958, 0.2380, 0.2621],
         [0.2842, 0.9633, 0.6489, 0.2329, 0.5306],
         [0.1958, 0.7084, 0.5265, 0.9228, 0.5801]],

        [[0.5621, 0.2295, 0.3116, 0.4237, 0.4300],
         [0.3891, 0.1177, 0.6552, 0.4001, 0.8315],
         [0.5020, 0.1340, 0.3936, 0.3479, 0.5690],
         [0.9737, 0.6566, 0.9133, 0.8860, 0.6550],
         [0.8897, 0.1659, 0.5994, 0.2447, 0.4253]],

        [[0.6758, 0.2233, 0.1595, 0.3236, 0.2762],
         [0.3482, 0.2082, 0.3498, 0.7722, 0.9337],
         [0.7588, 0.4611, 0.8162, 0.0691, 0.7052],
         [0.7427, 0.7207, 0.9146, 0.5633, 0.0325],
         [0.7342, 0.2215, 0.5160, 0.1582, 0.3223]]])

In [44]:
channel1 = t10[:, 0, :,:] # 0번째 컬러 채널만 가져오기

In [45]:
channel1

tensor([[[0.1100, 0.7883, 0.5993, 0.9477, 0.8325],
         [0.2156, 0.7145, 0.4367, 0.0315, 0.3926],
         [0.4098, 0.7815, 0.9958, 0.2380, 0.2621],
         [0.2842, 0.9633, 0.6489, 0.2329, 0.5306],
         [0.1958, 0.7084, 0.5265, 0.9228, 0.5801]],

        [[0.6049, 0.1758, 0.4152, 0.0223, 0.8323],
         [0.1581, 0.3767, 0.5381, 0.7620, 0.2892],
         [0.6185, 0.9758, 0.2122, 0.0867, 0.3426],
         [0.7099, 0.2646, 0.0581, 0.2585, 0.3734],
         [0.8059, 0.8953, 0.1700, 0.9697, 0.8106]]])

8. Tensor 차원 관련 수정

* 다른 라이브러리와 데이터 배열 형태가 다른 경우 변경이 필요합니다. 

In [47]:
# 차원 늘이기

t11 = torch.rand(5,5) # 흑백 이미지 한장 예시

In [53]:
# batch, channel 추가하기 

t12=t11.unsqueeze(dim=0)
print(t12.size())

torch.Size([1, 5, 5])


In [54]:
t13 = t12.unsqueeze(dim=0)

In [55]:
t13.size()

torch.Size([1, 1, 5, 5])

In [57]:
# 차원 줄이기

t13.squeeze().size()  # 1개인 차원이 모두 사라짐짐

torch.Size([5, 5])

In [61]:
t13.squeeze(dim=0).size() # 원하는 차원의 위치를 지정 가능함. 0부터 시작

torch.Size([1, 5, 5])

In [62]:
t13.squeeze(dim=2).size() # 차원이 1이 아니면 없어지지 않음, 데이터가 삭제되는 것을 방지

torch.Size([1, 1, 5, 5])

In [71]:
t13.permute(0,2,3,1).shape  # 컬러 채널 위치 변경

torch.Size([1, 5, 5, 1])