Neural Network 구성에 필수적인 nn.linear 함수를 알아봅시다. 

https://pytorch.org/docs/stable/generated/torch.nn.Linear.html

y = w*x + b를 계산할수 있습니다. 
데이터 학습을 통해 데이터에 맞는 w와 b를 구할 수 있습니다

In [ ]:
import torch
import torch.nn as nn

linear_layer = nn.Linear(1,1) 

In [ ]:
# weight와 bias는 초기에 random값으로 입력됩니다. (실행할 때마다 다른 결과값이 나옵니다. )

print(linear_layer.weight)
print(linear_layer.bias)

Parameter containing:
tensor([[-0.8635]], requires_grad=True)
Parameter containing:
tensor([0.3825], requires_grad=True)


In [ ]:
x = torch.tensor([3.0])
y = linear_layer(x)
print(y)

tensor([-2.2081], grad_fn=<AddBackward0>)
